(function initializeQuestionBank() {
  const currentYear = new Date().getFullYear();

  window.GUESSED = window.GUESSED || {};
  window.GUESSED.questionBank = {
    price: [
      { id: "price-001", type: "price", category: "PRICE", question: "How much does a weekly supermarket shop for two people cost?", answer: 86.42, unit: "Â£" },
      { id: "price-002", type: "price", category: "PRICE", question: "How much does an average takeaway pizza cost?", answer: 14.50, unit: "Â£" },
      { id: "price-003", type: "price", category: "PRICE", question: "How much does a pair of average running shoes cost?", answer: 95, unit: "Â£" },
      { id: "price-004", type: "price", category: "PRICE", question: "How much does a cinema ticket cost on average?", answer: 12, unit: "Â£" },
      { id: "price-005", type: "price", category: "PRICE", question: "How much does a three-course restaurant meal for two people cost?", answer: 75, unit: "Â£" },
      { id: "price-006", type: "price", category: "PRICE", question: "How much is a 1kg bag of Tesco Fusilli Pasta Twists?", answer: 1.19, unit: "£", source: "Tesco Groceries", sourceUrl: "https://www.tesco.com/shop/en-GB/products/254878499", dateChecked: "2026-10-02", subcategory: "food-drink", difficulty: "easy" },
      { id: "price-007", type: "price", category: "PRICE", question: "How much is a 1kg pack of Tesco British Chicken Breast Fillets?", answer: 6.90, unit: "£", source: "Tesco Groceries", sourceUrl: "https://www.tesco.com/shop/en-GB/search?query=tesco+chicken+breast+fillet+1kg", dateChecked: "2026-10-02", subcategory: "food-drink", difficulty: "medium" },
      { id: "price-008", type: "price", category: "PRICE", question: "How much is a 227g bag of Waitrose No.1 Colombia Reserve Ground Coffee?", answer: 4.75, unit: "£", source: "Waitrose & Partners", sourceUrl: "https://www.waitrose.com/ecom/products/no1-colombia-reserve-ground-coffee/079687-40543-40544", dateChecked: "2026-10-02", subcategory: "food-drink", difficulty: "medium" },
      { id: "price-009", type: "price", category: "PRICE", question: "How much is a 1-litre bottle of Waitrose Extra Virgin Olive Oil?", answer: 7.85, unit: "£", source: "Waitrose & Partners", sourceUrl: "https://www.waitrose.com/ecom/products/waitrose-extra-virgin-olive-oil/034147-17095-17096", dateChecked: "2026-10-02", subcategory: "food-drink", difficulty: "medium" },
      { id: "price-010", type: "price", category: "PRICE", question: "How much does the 256GB Apple iPhone 17 cost from Apple UK?", answer: 899, unit: "£", source: "Apple UK", sourceUrl: "https://www.apple.com/uk/shop/buy-iphone/iphone-17/6.3-inch-display-256gb-white", dateChecked: "2026-10-02", subcategory: "technology", difficulty: "medium" },
      { id: "price-011", type: "price", category: "PRICE", question: "How much does the 128GB Wi-Fi Apple iPad (A16) cost from Apple UK?", answer: 329, unit: "£", source: "Apple UK", sourceUrl: "https://www.apple.com/uk/shop/buy-ipad/ipad/64gb-blue-wifi?product=MQ6L3B%2FA&step=select", dateChecked: "2026-10-02", subcategory: "technology", difficulty: "easy" },
      { id: "price-012", type: "price", category: "PRICE", question: "How much does the standard 1TB PlayStation 5 console cost from PlayStation Direct UK?", answer: 569, unit: "£", source: "PlayStation Direct UK", sourceUrl: "https://direct.playstation.com/en-gb/hardware/ps5/", dateChecked: "2026-10-02", subcategory: "technology", difficulty: "medium" },
      { id: "price-013", type: "price", category: "PRICE", question: "How much does the 256GB Samsung Galaxy S25 cost from Samsung UK?", answer: 889, unit: "£", source: "Samsung UK", sourceUrl: "https://www.samsung.com/uk/smartphones/galaxy-s25/buy/", dateChecked: "2026-10-02", subcategory: "technology", difficulty: "difficult" },
      { id: "price-014", type: "price", category: "PRICE", question: "What is the adult peak pay-as-you-go fare for a single Zone 1 journey on TfL?", answer: 3.10, unit: "£", source: "Transport for London", sourceUrl: "https://tfl.gov.uk/campaign/fares-from-2-march-2025", dateChecked: "2026-10-02", subcategory: "travel", difficulty: "easy" },
      { id: "price-015", type: "price", category: "PRICE", question: "What is the advertised starting price for a one-way Heathrow Express ticket between Heathrow Airport and London Paddington?", answer: 10, unit: "£", source: "Heathrow Express", sourceUrl: "https://www.heathrowexpress.com/", dateChecked: "2026-10-02", subcategory: "travel", difficulty: "medium" },
      { id: "price-016", type: "price", category: "PRICE", question: "What is the advertised starting one-way ticket price for ScotRail from Glasgow Queen Street to Edinburgh Waverley?", answer: 16.80, unit: "£", source: "ScotRail", sourceUrl: "https://www.scotrail.co.uk/train-times/glasgow-queen-street-to-edinburgh-waverley", dateChecked: "2026-10-02", subcategory: "travel", difficulty: "difficult" },
      { id: "price-017", type: "price", category: "PRICE", question: "How much is one adult ticket for standard admission to the Tower of London, without a donation?", answer: 37, unit: "£", source: "Historic Royal Palaces", sourceUrl: "https://www.hrp.org.uk/tower-of-london/visit/tickets-and-prices/", dateChecked: "2026-10-02", subcategory: "entertainment", difficulty: "medium" },
      { id: "price-018", type: "price", category: "PRICE", question: "How much is Netflix's UK Standard with adverts plan per month?", answer: 7.99, unit: "£", source: "Netflix UK", sourceUrl: "https://www.netflix.com/gb/", dateChecked: "2026-10-02", subcategory: "entertainment", difficulty: "easy" },
      { id: "price-019", type: "price", category: "PRICE", question: "How much is Spotify Premium Individual per month in the UK after any introductory offer?", answer: 12.99, unit: "£", source: "Spotify UK", sourceUrl: "https://www.spotify.com/uk/premium/", dateChecked: "2026-10-02", subcategory: "entertainment", difficulty: "medium" },
      { id: "price-020", type: "price", category: "PRICE", question: "How much does a UK 1st Class stamp for a standard letter cost?", answer: 1.80, unit: "£", source: "Royal Mail", sourceUrl: "https://www.royalmail.com/sending/stamps", dateChecked: "2026-10-02", subcategory: "everyday-life", difficulty: "easy" },
      { id: "price-021", type: "price", category: "PRICE", question: "What is the NHS prescription charge per item in England?", answer: 9.90, unit: "£", source: "NHS Business Services Authority", sourceUrl: "https://www.nhsbsa.nhs.uk/help-nhs-prescription-costs/nhs-prescription-prepayment-certificate-ppc", dateChecked: "2026-10-02", subcategory: "everyday-life", difficulty: "medium" },
      { id: "price-022", type: "price", category: "PRICE", question: "How much does an annual colour TV Licence cost in the UK for 2026/27?", answer: 180, unit: "£", source: "GOV.UK / Department for Culture, Media and Sport", sourceUrl: "https://www.gov.uk/government/news/cost-of-tv-licence-fee-set-for-202627", dateChecked: "2026-10-02", subcategory: "everyday-life", difficulty: "medium" },
      { id: "price-023", type: "price", category: "PRICE", question: "How much does Fortnum & Mason's Fortmason Hamper cost?", answer: 150, unit: "£", source: "Fortnum & Mason", sourceUrl: "https://www.fortnumandmason.com/hampers/hampers-by-price-point", dateChecked: "2026-10-02", subcategory: "luxury-interesting", difficulty: "difficult" },
      { id: "price-024", type: "price", category: "PRICE", question: "How much does the 9,090-piece LEGO Icons Titanic set cost from LEGO UK?", answer: 589.99, unit: "£", source: "LEGO Shop GB", sourceUrl: "https://www.lego.com/en-gb/themes/lego-icons", dateChecked: "2026-10-02", subcategory: "luxury-interesting", difficulty: "difficult" },
      { id: "price-025", type: "price", category: "PRICE", question: "How much does Harrods' in-store-only Ultimate Christmas Hamper cost?", answer: 5500, unit: "£", source: "Harrods UK", sourceUrl: "https://www.harrods.com/en-gb/designers/harrods/food-drink/hampers/christmas-hampers", dateChecked: "2026-10-02", subcategory: "luxury-interesting", difficulty: "difficult" }
    ],
    scale: [
      { id: "scale-001", type: "scale", category: "SCALE", question: "How tall is the Eiffel Tower?", answer: 330, unit: "m", min: 0, max: 500 },
      { id: "scale-002", type: "scale", category: "SCALE", question: "How high is Big Ben?", answer: 96, unit: "m", min: 0, max: 150 },
      { id: "scale-003", type: "scale", category: "SCALE", question: "How long is an Olympic swimming pool?", answer: 50, unit: "m", min: 0, max: 100 },
      { id: "scale-004", type: "scale", category: "SCALE", question: "How tall is the Statue of Liberty?", answer: 93, unit: "m", min: 0, max: 150 },
      { id: "scale-005", type: "scale", category: "SCALE", question: "How long is a Boeing 747-8?", answer: 76, unit: "m", min: 0, max: 120 },
      { id: "scale-006", type: "scale", category: "SCALE", question: "How tall was the Great Pyramid of Giza when it was originally built?", answer: 146.5, unit: "m", min: 0, max: 300, source: "Egyptian Ministry of Tourism and Antiquities", sourceUrl: "https://egymonuments.gov.eg/monuments/the-great-pyramid/", dateChecked: "2026-10-02", subcategory: "buildings-structures", difficulty: "medium" },
      { id: "scale-007", type: "scale", category: "SCALE", question: "How long is the main suspension span of the Golden Gate Bridge, from tower to tower?", answer: 1280, unit: "m", min: 0, max: 3000, source: "Golden Gate Bridge, Highway and Transportation District", sourceUrl: "https://www.goldengate.org/bridge/history-research/statistics-data/design-construction-stats/", dateChecked: "2026-10-02", subcategory: "buildings-structures", difficulty: "medium" },
      { id: "scale-008", type: "scale", category: "SCALE", question: "What is the upper end of the reported mass range for an adult male African bush elephant?", answer: 6100, unit: "kg", min: 0, max: 10000, source: "Animal Diversity Web, University of Michigan", sourceUrl: "https://animaldiversity.org/accounts/Loxodonta_africana/", dateChecked: "2026-10-02", subcategory: "animals", difficulty: "medium" },
      { id: "scale-009", type: "scale", category: "SCALE", question: "According to the Smithsonian's National Zoo, what is the top end of a cheetah's speed range?", answer: 112, unit: "km/h", min: 0, max: 150, source: "Smithsonian's National Zoo and Conservation Biology Institute", sourceUrl: "https://nationalzoo.si.edu/animals/cheetah", dateChecked: "2026-10-02", subcategory: "animals", difficulty: "easy" },
      { id: "scale-010", type: "scale", category: "SCALE", question: "How tall can a male reticulated giraffe grow, according to the Maryland Zoo?", answer: 5.5, unit: "m", min: 0, max: 10, source: "The Maryland Zoo", sourceUrl: "https://www.marylandzoo.org/animal/reticulated-giraffe/", dateChecked: "2026-10-02", subcategory: "animals", difficulty: "easy" },
      { id: "scale-011", type: "scale", category: "SCALE", question: "How long can an Antarctic blue whale grow, according to NOAA Fisheries?", answer: 33.5, unit: "m", min: 0, max: 40, source: "NOAA Fisheries", sourceUrl: "https://www.fisheries.noaa.gov/species/blue-whale", dateChecked: "2026-10-02", subcategory: "animals", difficulty: "difficult" },
      { id: "scale-012", type: "scale", category: "SCALE", question: "What is Mount Everest's official elevation above sea level?", answer: 8848.86, unit: "m", min: 0, max: 10000, source: "Government of Nepal, Department of Tourism", sourceUrl: "https://www.tourismdepartment.gov.np/files/statistics/45.pdf", dateChecked: "2026-10-02", subcategory: "geography", difficulty: "medium" },
      { id: "scale-013", type: "scale", category: "SCALE", question: "How long is the Grand Canyon when measured along the Colorado River?", answer: 446, unit: "km", min: 0, max: 1000, source: "U.S. National Park Service", sourceUrl: "https://www.nps.gov/grca/faqs.htm", dateChecked: "2026-10-02", subcategory: "geography", difficulty: "medium" },
      { id: "scale-014", type: "scale", category: "SCALE", question: "How deep was the deepest observed seafloor at Challenger Deep in a NOAA study?", answer: 10935, unit: "m", min: 0, max: 12000, source: "NOAA Central Library", sourceUrl: "https://repository.library.noaa.gov/view/noaa/33477", dateChecked: "2026-10-02", subcategory: "geography", difficulty: "difficult" },
      { id: "scale-015", type: "scale", category: "SCALE", question: "What is the average distance from Earth to the Moon?", answer: 384400, unit: "km", min: 0, max: 500000, source: "NASA Science", sourceUrl: "https://science.nasa.gov/moon/by-the-numbers/", dateChecked: "2026-10-02", subcategory: "geography", difficulty: "difficult" },
      { id: "scale-016", type: "scale", category: "SCALE", question: "What is the curb mass of the rear-wheel-drive Tesla Model 3 listed by Tesla UK?", answer: 1772, unit: "kg", min: 0, max: 3000, source: "Tesla UK", sourceUrl: "https://www.tesla.com/en_GB/model3", dateChecked: "2026-10-02", subcategory: "vehicles", difficulty: "medium" },
      { id: "scale-017", type: "scale", category: "SCALE", question: "What is the unladen weight of a London New Routemaster double-decker bus?", answer: 12.4, unit: "tonnes", min: 0, max: 25, source: "London Assembly", sourceUrl: "https://www.london.gov.uk/who-we-are/what-london-assembly-does/questions-mayor/find-an-answer/new-bus-london-vehicle-weight-1", dateChecked: "2026-10-02", subcategory: "vehicles", difficulty: "medium" },
      { id: "scale-018", type: "scale", category: "SCALE", question: "How long is the standard marathon race distance?", answer: 42.195, unit: "km", min: 0, max: 100, source: "World Athletics", sourceUrl: "https://worldathletics.org/disciplines/roadrunning/marathon", dateChecked: "2026-10-02", subcategory: "sport", difficulty: "easy" },
      { id: "scale-019", type: "scale", category: "SCALE", question: "How much does the shot used in senior men's elite shot put weigh?", answer: 7.26, unit: "kg", min: 0, max: 20, source: "World Athletics", sourceUrl: "https://worldathletics.org/disciplines/throws/shot-put", dateChecked: "2026-10-02", subcategory: "sport", difficulty: "medium" },
      { id: "scale-020", type: "scale", category: "SCALE", question: "How long is the long edge of a standard A4 sheet of paper?", answer: 297, unit: "mm", min: 0, max: 500, source: "HP Support, ISO 216 paper sizes", sourceUrl: "https://support.hp.com/gb-en/document/bpq04022", dateChecked: "2026-10-02", subcategory: "everyday-objects", difficulty: "easy" },
      { id: "scale-021", type: "scale", category: "SCALE", question: "How many millilitres are in an imperial pint?", answer: 568, unit: "ml", min: 0, max: 1000, source: "GOV.UK, Weights and Measures Regulations", sourceUrl: "https://www.gov.uk/guidance/packaged-goods-weights-and-measures-regulations", dateChecked: "2026-10-02", subcategory: "everyday-objects", difficulty: "easy" },
      { id: "scale-022", type: "scale", category: "SCALE", question: "How long is the current polymer Bank of England £5 note?", answer: 125, unit: "mm", min: 0, max: 250, source: "Bank of England", sourceUrl: "https://www.bankofengland.co.uk/banknotes/5-pound-note", dateChecked: "2026-10-02", subcategory: "everyday-objects", difficulty: "medium" },
      { id: "scale-023", type: "scale", category: "SCALE", question: "How fast does the International Space Station travel in orbit, according to NASA?", answer: 28000, unit: "km/h", min: 0, max: 40000, source: "NASA", sourceUrl: "https://www.nasa.gov/missions/station/spot-the-station-frequently-asked-questions/", dateChecked: "2026-10-02", subcategory: "weird-interesting", difficulty: "difficult" },
      { id: "scale-024", type: "scale", category: "SCALE", question: "What is the approximate diameter of a typical DNA double helix?", answer: 2, unit: "nm", min: 0, max: 10, source: "NCBI Bookshelf, The Cell", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK9944/", dateChecked: "2026-10-02", subcategory: "weird-interesting", difficulty: "difficult" },
      { id: "scale-025", type: "scale", category: "SCALE", question: "What is the approximate temperature of the Sun's photosphere?", answer: 5500, unit: "°C", min: 0, max: 10000, source: "NASA Earth Observatory", sourceUrl: "https://science.nasa.gov/earth/earth-observatory/climate-and-earths-energy-budget/", dateChecked: "2026-10-02", subcategory: "weird-interesting", difficulty: "medium" }
    ],
    human: [
      { id: "human-001", type: "human", category: "HUMAN", question: "What percentage of people have Googled their own name?", answer: 42, unit: "%", verified: false },
      { id: "human-002", type: "human", category: "HUMAN", question: "What percentage of people admit to talking to themselves?", answer: 57, unit: "%", verified: false },
      { id: "human-003", type: "human", category: "HUMAN", question: "What percentage of people have pretended to understand something when they did not?", answer: 68, unit: "%", verified: false },
      { id: "human-004", type: "human", category: "HUMAN", question: "What percentage of people check their phone within 10 minutes of waking up?", answer: 62, unit: "%", verified: false },
      { id: "human-005", type: "human", category: "HUMAN", question: "What percentage of people have lied about being busy to avoid making plans?", answer: 41, unit: "%", verified: false },
      { id: "human-006", type: "human", category: "HUMAN", subcategory: "money-spending", question: "In the FCA's 2024 UK survey, what percentage of adults said they occasionally use cash in day-to-day life?", answer: 44, unit: "%", verified: true, source: "Financial Conduct Authority, Financial Lives 2024", sourceUrl: "https://www.fca.org.uk/publication/financial-lives/fls-2024-payments.pdf", dateChecked: "2026-10-02", dataYear: 2024, population: "UK adults", sampleSize: 17950, difficulty: "medium" },
      { id: "human-007", type: "human", category: "HUMAN", subcategory: "money-spending", question: "In the FCA's 2024 UK survey, what percentage of adults said they use cash and other payment methods equally?", answer: 21, unit: "%", verified: true, source: "Financial Conduct Authority, Financial Lives 2024", sourceUrl: "https://www.fca.org.uk/publication/financial-lives/fls-2024-payments.pdf", dateChecked: "2026-10-02", dataYear: 2024, population: "UK adults", sampleSize: 17950, difficulty: "difficult" },
      { id: "human-008", type: "human", category: "HUMAN", subcategory: "money-spending", question: "In the FCA's 2024 UK survey, what percentage of adults said they almost always use other payment methods, even for everyday purchases?", answer: 31, unit: "%", verified: true, source: "Financial Conduct Authority, Financial Lives 2024", sourceUrl: "https://www.fca.org.uk/publication/financial-lives/fls-2024-payments.pdf", dateChecked: "2026-10-02", dataYear: 2024, population: "UK adults", sampleSize: 17950, difficulty: "medium" },
      { id: "human-009", type: "human", category: "HUMAN", subcategory: "technology-social-media", question: "In a January 2025 YouGov poll, what percentage of GB adults said they had used an AI chatbot such as ChatGPT?", answer: 40, unit: "%", verified: true, source: "YouGov Daily Question, 29 January 2025", sourceUrl: "https://yougov.co.uk/topics/technology/survey-results/daily/2025/01/29/17c41/3", dateChecked: "2026-10-02", dataYear: 2025, population: "GB adults", sampleSize: 4726, difficulty: "medium" },
      { id: "human-010", type: "human", category: "HUMAN", subcategory: "technology-social-media", question: "In Ofcom's 2023 media use research, what percentage of adults said they deliberately take breaks from social media apps?", answer: 22, unit: "%", verified: true, source: "Ofcom, Adults' Media Use and Attitudes Report 2024", sourceUrl: "https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/media-literacy-research/adults/adults-media-use-and-attitudes-2024/adults-media-use-and-attitudes-report-2024.pdf", dateChecked: "2026-10-02", dataYear: 2023, population: "UK adults using social media", difficulty: "difficult" },
      { id: "human-011", type: "human", category: "HUMAN", subcategory: "technology-social-media", question: "In Ofcom's 2023 media use research, what percentage of adults said they disable notifications or use Do Not Disturb to manage online time?", answer: 26, unit: "%", verified: true, source: "Ofcom, Adults' Media Use and Attitudes Report 2024", sourceUrl: "https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/media-literacy-research/adults/adults-media-use-and-attitudes-2024/adults-media-use-and-attitudes-report-2024.pdf", dateChecked: "2026-10-02", dataYear: 2023, population: "UK adult internet users", difficulty: "easy" },
      { id: "human-012", type: "human", category: "HUMAN", subcategory: "technology-social-media", question: "In Ofcom's 2023 media use research, what percentage of adults said they choose not to take their phone or tablet to bed?", answer: 21, unit: "%", verified: true, source: "Ofcom, Adults' Media Use and Attitudes Report 2024", sourceUrl: "https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/media-literacy-research/adults/adults-media-use-and-attitudes-2024/adults-media-use-and-attitudes-report-2024.pdf", dateChecked: "2026-10-02", dataYear: 2023, population: "UK adult internet users", difficulty: "medium" },
      { id: "human-013", type: "human", category: "HUMAN", subcategory: "food-lifestyle", question: "In a March 2024 YouGov poll, what percentage of GB adults said they plan what to eat for the week ahead in advance?", answer: 48, unit: "%", verified: true, source: "YouGov Daily Question, 6 March 2024", sourceUrl: "https://yougov.co.uk/topics/consumer/survey-results/daily/2024/03/06/b2be0/3", dateChecked: "2026-10-02", dataYear: 2024, population: "GB adults", sampleSize: 3542, difficulty: "easy" },
      { id: "human-014", type: "human", category: "HUMAN", subcategory: "food-lifestyle", question: "In a 2024 YouGov poll, what percentage of GB adults who eat pizza said they love pineapple as a topping?", answer: 25, unit: "%", verified: true, source: "YouGov Daily Question, 11 January 2024", sourceUrl: "https://yougov.co.uk/topics/consumer/survey-results/daily/2024/01/11/e2271/3", dateChecked: "2026-10-02", dataYear: 2024, population: "GB adults", sampleSize: 2845, difficulty: "medium" },
      { id: "human-015", type: "human", category: "HUMAN", subcategory: "food-lifestyle", question: "In a 2025 YouGov poll, what percentage of GB adults said they prefer to drink cola from a glass?", answer: 33, unit: "%", verified: true, source: "YouGov Daily Question, 29 April 2025", sourceUrl: "https://yougov.co.uk/topics/consumer/survey-results/daily/2025/04/29/68fc6/3", dateChecked: "2026-10-02", dataYear: 2025, population: "GB adults", sampleSize: 4589, difficulty: "medium" },
      { id: "human-016", type: "human", category: "HUMAN", subcategory: "relationships-social-behaviour", question: "In a May 2024 YouGov poll, what percentage of GB adults preferred the other person to make the first move when dating?", answer: 48, unit: "%", verified: true, source: "YouGov Daily Question, 2 May 2024", sourceUrl: "https://yougov.co.uk/topics/society/survey-results/daily/2024/05/02/de5b7/1", dateChecked: "2026-10-02", dataYear: 2024, population: "GB adults", sampleSize: 4973, difficulty: "medium" },
      { id: "human-017", type: "human", category: "HUMAN", subcategory: "relationships-social-behaviour", question: "In a September 2024 YouGov poll, what percentage of GB adults said they fairly often forget people's birthdays?", answer: 27, unit: "%", verified: true, source: "YouGov Daily Question, 3 September 2024", sourceUrl: "https://yougov.co.uk/topics/society/survey-results/daily/2024/09/03/43ee2/2", dateChecked: "2026-10-02", dataYear: 2024, population: "GB adults", sampleSize: 3329, difficulty: "difficult" },
      { id: "human-018", type: "human", category: "HUMAN", subcategory: "relationships-social-behaviour", question: "In a February 2024 YouGov poll, what percentage of GB adults said they were currently in love with someone?", answer: 60, unit: "%", verified: true, source: "YouGov Daily Question, 14 February 2024", sourceUrl: "https://yougov.co.uk/topics/society/survey-results/daily/2024/02/14/df4cb/3", dateChecked: "2026-10-02", dataYear: 2024, population: "GB adults", sampleSize: 2474, difficulty: "easy" },
      { id: "human-019", type: "human", category: "HUMAN", subcategory: "work-education", question: "According to the ONS in autumn 2024, what percentage of working adults in Great Britain were hybrid working?", answer: 28, unit: "%", verified: true, source: "Office for National Statistics, Who are the hybrid workers?", sourceUrl: "https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/articles/whoarethehybridworkers/2024-11-11", dateChecked: "2026-10-02", dataYear: 2024, population: "Working adults in Great Britain", difficulty: "medium" },
      { id: "human-020", type: "human", category: "HUMAN", subcategory: "work-education", question: "In ONS data collected in spring 2024, what percentage of working adults with a degree or equivalent qualification were hybrid working?", answer: 42, unit: "%", verified: true, source: "Office for National Statistics, Who are the hybrid workers?", sourceUrl: "https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/articles/whoarethehybridworkers/2024-11-11", dateChecked: "2026-10-02", dataYear: 2024, population: "Working adults in Great Britain with a degree or equivalent", difficulty: "difficult" },
      { id: "human-021", type: "human", category: "HUMAN", subcategory: "work-education", question: "In ONS data collected in spring 2024, what percentage of working adults in elementary occupations were hybrid working?", answer: 3, unit: "%", verified: true, source: "Office for National Statistics, Who are the hybrid workers?", sourceUrl: "https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/articles/whoarethehybridworkers/2024-11-11", dateChecked: "2026-10-02", dataYear: 2024, population: "Working adults in Great Britain in elementary occupations", difficulty: "medium" },
      { id: "human-022", type: "human", category: "HUMAN", subcategory: "uk-specific-behaviour", question: "In a February 2020 YouGov poll, what percentage of GB adults said it was acceptable to keep earphones in while buying something in a shop?", answer: 16, unit: "%", verified: true, source: "YouGov Daily Question, 13 February 2020", sourceUrl: "https://yougov.co.uk/topics/lifestyle/survey-results/daily/2020/02/13/4e072/3", dateChecked: "2026-10-02", dataYear: 2020, population: "GB adults", sampleSize: 2515, difficulty: "difficult" },
      { id: "human-023", type: "human", category: "HUMAN", subcategory: "uk-specific-behaviour", question: "In a December 2023 YouGov poll, what percentage of GB adults said they turn on the shower just before getting in?", answer: 56, unit: "%", verified: true, source: "YouGov Daily Question, 20 December 2023", sourceUrl: "https://yougov.co.uk/topics/society/survey-results/daily/2023/12/20/76fc4/3", dateChecked: "2026-10-02", dataYear: 2023, population: "GB adults", sampleSize: 2539, difficulty: "easy" },
      { id: "human-024", type: "human", category: "HUMAN", subcategory: "weird-interesting", question: "In a December 2022 YouGov poll, what percentage of GB adults said they never read their horoscope?", answer: 56, unit: "%", verified: true, source: "YouGov Daily Question, 30 December 2022", sourceUrl: "https://yougov.co.uk/topics/society/survey-results/daily/2022/12/30/0b4f1/2", dateChecked: "2026-10-02", dataYear: 2022, population: "GB adults", sampleSize: 3122, difficulty: "easy" },
      { id: "human-025", type: "human", category: "HUMAN", subcategory: "weird-interesting", question: "In a December 2023 YouGov poll, what percentage of GB adults said they turn on the shower only once they are already in it?", answer: 17, unit: "%", verified: true, source: "YouGov Daily Question, 20 December 2023", sourceUrl: "https://yougov.co.uk/topics/society/survey-results/daily/2023/12/20/76fc4/3", dateChecked: "2026-10-02", dataYear: 2023, population: "GB adults", sampleSize: 2539, difficulty: "medium" }
    ],
    crowd: [
      { id: "crowd-001", type: "crowd", category: "CROWD", question: "Which country do you think people most strongly associate with pizza?", options: [{ id: "italy", label: "Italy", emoji: "ðŸ‡®ðŸ‡¹" }, { id: "usa", label: "USA", emoji: "ðŸ‡ºðŸ‡¸" }, { id: "uk", label: "United Kingdom", emoji: "ðŸ‡¬ðŸ‡§" }, { id: "france", label: "France", emoji: "ðŸ‡«ðŸ‡·" }], crowdDistribution: { italy: 64, usa: 21, uk: 9, france: 6 }, dataStatus: "simulated" },
      { id: "crowd-002", type: "crowd", category: "CROWD", question: "Which of these would most people choose for a lazy Sunday?", options: [{ id: "tv", label: "Watching TV", emoji: "ðŸ“º" }, { id: "walk", label: "Going for a walk", emoji: "ðŸš¶" }, { id: "friends", label: "Going out with friends", emoji: "ðŸ§‘â€ðŸ¤â€ðŸ§‘" }, { id: "games", label: "Playing video games", emoji: "ðŸŽ®" }], crowdDistribution: { tv: 43, walk: 14, friends: 24, games: 19 }, dataStatus: "simulated" },
      { id: "crowd-003", type: "crowd", category: "CROWD", question: "Which food would most people struggle to give up for a month?", options: [{ id: "chocolate", label: "Chocolate", emoji: "ðŸ«" }, { id: "pizza", label: "Pizza", emoji: "ðŸ•" }, { id: "coffee", label: "Coffee", emoji: "â˜•" }, { id: "crisps", label: "Crisps", emoji: "ðŸ¥”" }], crowdDistribution: { chocolate: 34, pizza: 29, coffee: 25, crisps: 12 }, dataStatus: "simulated" },
      { id: "crowd-004", type: "crowd", category: "CROWD", question: "Which app do you think people would be most reluctant to delete for a month?", options: [{ id: "whatsapp", label: "WhatsApp", emoji: "ðŸ’¬" }, { id: "instagram", label: "Instagram", emoji: "ðŸ“¸" }, { id: "youtube", label: "YouTube", emoji: "â–¶ï¸" }, { id: "tiktok", label: "TikTok", emoji: "ðŸŽµ" }], crowdDistribution: { whatsapp: 28, instagram: 31, youtube: 24, tiktok: 17 }, dataStatus: "simulated" },
      { id: "crowd-005", type: "crowd", category: "CROWD", question: "If someone gave you Â£1,000 and said you had to spend it today, what would most people choose to do?", options: [{ id: "holiday", label: "Go on holiday", emoji: "ðŸ–ï¸" }, { id: "expensive", label: "Buy something expensive", emoji: "ðŸ›ï¸" }, { id: "save", label: "Save it", emoji: "ðŸ¦" }, { id: "celebrate", label: "Go out and celebrate", emoji: "ðŸŽ‰" }], crowdDistribution: { holiday: 39, expensive: 18, save: 31, celebrate: 12 }, dataStatus: "simulated" },
      { id: "crowd-006", type: "crowd", category: "CROWD", subcategory: "food-drink", question: "Which takeaway would people most likely pick for a Friday night?", options: [{ id: "pizza", label: "Pizza", emoji: "🍕" }, { id: "curry", label: "Curry", emoji: "🍛" }, { id: "burgers", label: "Burgers", emoji: "🍔" }, { id: "chinese", label: "Chinese", emoji: "🥡" }], crowdDistribution: { pizza: 36, curry: 28, burgers: 21, chinese: 15 }, dataStatus: "simulated", difficulty: "easy" },
      { id: "crowd-007", type: "crowd", category: "CROWD", subcategory: "food-drink", question: "Which drink would people most want with breakfast?", options: [{ id: "tea", label: "Tea", emoji: "🫖" }, { id: "coffee", label: "Coffee", emoji: "☕" }, { id: "juice", label: "Orange juice", emoji: "🧃" }, { id: "water", label: "Water", emoji: "💧" }], crowdDistribution: { tea: 31, coffee: 34, juice: 20, water: 15 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-008", type: "crowd", category: "CROWD", subcategory: "food-drink", question: "Which dessert would people choose at a restaurant?", options: [{ id: "cheesecake", label: "Cheesecake", emoji: "🍰" }, { id: "brownie", label: "Chocolate brownie", emoji: "🍫" }, { id: "ice-cream", label: "Ice cream", emoji: "🍨" }, { id: "sticky-toffee", label: "Sticky toffee pudding", emoji: "🍮" }], crowdDistribution: { cheesecake: 27, brownie: 29, "ice-cream": 25, "sticky-toffee": 19 }, dataStatus: "simulated", difficulty: "difficult" },
      { id: "crowd-009", type: "crowd", category: "CROWD", subcategory: "travel-experiences", question: "Which free weekend escape would people pick?", options: [{ id: "beach", label: "Beach break", emoji: "🏖️" }, { id: "city", label: "City break", emoji: "🏙️" }, { id: "countryside", label: "Countryside", emoji: "🌳" }, { id: "stay-home", label: "Stay at home", emoji: "🏠" }], crowdDistribution: { beach: 35, city: 25, countryside: 22, "stay-home": 18 }, dataStatus: "simulated", difficulty: "easy" },
      { id: "crowd-010", type: "crowd", category: "CROWD", subcategory: "travel-experiences", question: "Which would people rather do on a day off?", options: [{ id: "spa", label: "Spa day", emoji: "🧖" }, { id: "museum", label: "Visit a museum", emoji: "🖼️" }, { id: "hike", label: "Go for a hike", emoji: "🥾" }, { id: "theme-park", label: "Theme park", emoji: "🎢" }], crowdDistribution: { spa: 26, museum: 18, hike: 27, "theme-park": 29 }, dataStatus: "simulated", difficulty: "difficult" },
      { id: "crowd-011", type: "crowd", category: "CROWD", subcategory: "travel-experiences", question: "Which holiday activity would people choose first?", options: [{ id: "pool", label: "Relax by the pool", emoji: "🏊" }, { id: "sightseeing", label: "See the sights", emoji: "📸" }, { id: "local-food", label: "Try local food", emoji: "🍽️" }, { id: "shopping", label: "Go shopping", emoji: "🛍️" }], crowdDistribution: { pool: 38, sightseeing: 27, "local-food": 23, shopping: 12 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-012", type: "crowd", category: "CROWD", subcategory: "entertainment", question: "What would people most likely choose for a film night?", options: [{ id: "comedy", label: "Comedy", emoji: "😂" }, { id: "action", label: "Action", emoji: "💥" }, { id: "thriller", label: "Thriller", emoji: "🕵️" }, { id: "romance", label: "Romance", emoji: "💞" }], crowdDistribution: { comedy: 34, action: 30, thriller: 22, romance: 14 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-013", type: "crowd", category: "CROWD", subcategory: "entertainment", question: "Which live event would people most want tickets for?", options: [{ id: "concert", label: "Concert", emoji: "🎤" }, { id: "football", label: "Football match", emoji: "⚽" }, { id: "comedy-show", label: "Comedy show", emoji: "🎭" }, { id: "theatre", label: "Theatre show", emoji: "🎟️" }], crowdDistribution: { concert: 41, football: 32, "comedy-show": 16, theatre: 11 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-014", type: "crowd", category: "CROWD", subcategory: "entertainment", question: "Which kind of series would people pick to binge-watch?", options: [{ id: "crime", label: "Crime drama", emoji: "🔍" }, { id: "sitcom", label: "Sitcom", emoji: "🤣" }, { id: "fantasy", label: "Fantasy", emoji: "🐉" }, { id: "reality", label: "Reality TV", emoji: "📺" }], crowdDistribution: { crime: 29, sitcom: 24, fantasy: 25, reality: 22 }, dataStatus: "simulated", difficulty: "difficult" },
      { id: "crowd-015", type: "crowd", category: "CROWD", subcategory: "everyday-life", question: "Which household chore would people most like to never do again?", options: [{ id: "dishes", label: "Washing dishes", emoji: "🍽️" }, { id: "laundry", label: "Doing laundry", emoji: "🧺" }, { id: "vacuuming", label: "Vacuuming", emoji: "🧹" }, { id: "bathroom", label: "Cleaning bathroom", emoji: "🛁" }], crowdDistribution: { dishes: 28, laundry: 26, vacuuming: 21, bathroom: 25 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-016", type: "crowd", category: "CROWD", subcategory: "everyday-life", question: "What would people most likely do with an unexpected free hour?", options: [{ id: "nap", label: "Take a nap", emoji: "😴" }, { id: "scroll", label: "Scroll their phone", emoji: "📱" }, { id: "walk", label: "Go for a walk", emoji: "🚶" }, { id: "snack", label: "Make a snack", emoji: "🥪" }], crowdDistribution: { nap: 24, scroll: 39, walk: 20, snack: 17 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-017", type: "crowd", category: "CROWD", subcategory: "everyday-life", question: "Which small luxury would people choose for a tough week?", options: [{ id: "takeaway", label: "A takeaway", emoji: "🥡" }, { id: "new-book", label: "A new book", emoji: "📚" }, { id: "fancy-coffee", label: "Fancy coffee", emoji: "☕" }, { id: "long-bath", label: "A long bath", emoji: "🛀" }], crowdDistribution: { takeaway: 32, "new-book": 18, "fancy-coffee": 27, "long-bath": 23 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-018", type: "crowd", category: "CROWD", subcategory: "sport", question: "Which sport would people most enjoy watching live?", options: [{ id: "football", label: "Football", emoji: "⚽" }, { id: "tennis", label: "Tennis", emoji: "🎾" }, { id: "rugby", label: "Rugby", emoji: "🏉" }, { id: "formula-one", label: "Formula 1", emoji: "🏎️" }], crowdDistribution: { football: 46, tennis: 20, rugby: 16, "formula-one": 18 }, dataStatus: "simulated", difficulty: "easy" },
      { id: "crowd-019", type: "crowd", category: "CROWD", subcategory: "sport", question: "Which sporting achievement would people find most impressive?", options: [{ id: "marathon", label: "Run a marathon", emoji: "🏃" }, { id: "olympic-medal", label: "Win Olympic medal", emoji: "🥇" }, { id: "everest", label: "Climb Everest", emoji: "🏔️" }, { id: "world-record", label: "Set world record", emoji: "🏆" }], crowdDistribution: { marathon: 19, "olympic-medal": 34, everest: 27, "world-record": 20 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-020", type: "crowd", category: "CROWD", subcategory: "technology", question: "Which device would people find hardest to give up for a week?", options: [{ id: "phone", label: "Smartphone", emoji: "📱" }, { id: "laptop", label: "Laptop", emoji: "💻" }, { id: "tv", label: "Television", emoji: "📺" }, { id: "headphones", label: "Headphones", emoji: "🎧" }], crowdDistribution: { phone: 63, laptop: 18, tv: 12, headphones: 7 }, dataStatus: "simulated", difficulty: "easy" },
      { id: "crowd-021", type: "crowd", category: "CROWD", subcategory: "technology", question: "Which feature would people most want in a new phone?", options: [{ id: "battery", label: "Longer battery", emoji: "🔋" }, { id: "camera", label: "Better camera", emoji: "📷" }, { id: "storage", label: "More storage", emoji: "💾" }, { id: "durability", label: "More durable", emoji: "🛡️" }], crowdDistribution: { battery: 37, camera: 31, storage: 17, durability: 15 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-022", type: "crowd", category: "CROWD", subcategory: "british-culture", question: "Which British weather would people prefer for a day out?", options: [{ id: "sunny", label: "Bright sunshine", emoji: "☀️" }, { id: "cool-dry", label: "Cool and dry", emoji: "🌤️" }, { id: "cloudy", label: "Overcast", emoji: "☁️" }, { id: "light-rain", label: "Light rain", emoji: "🌦️" }], crowdDistribution: { sunny: 61, "cool-dry": 25, cloudy: 9, "light-rain": 5 }, dataStatus: "simulated", difficulty: "easy" },
      { id: "crowd-023", type: "crowd", category: "CROWD", subcategory: "british-culture", question: "What would people most want to find at a village fete?", options: [{ id: "cake", label: "Homemade cake", emoji: "🧁" }, { id: "raffle", label: "A raffle prize", emoji: "🎟️" }, { id: "crafts", label: "Local crafts", emoji: "🧶" }, { id: "games", label: "Old-fashioned games", emoji: "🎯" }], crowdDistribution: { cake: 33, raffle: 28, crafts: 17, games: 22 }, dataStatus: "simulated", difficulty: "medium" },
      { id: "crowd-024", type: "crowd", category: "CROWD", subcategory: "personal-preferences", question: "Which birthday treat would people be happiest to receive?", options: [{ id: "meal", label: "A meal out", emoji: "🍽️" }, { id: "cash", label: "Cash", emoji: "💷" }, { id: "experience", label: "An experience", emoji: "🎫" }, { id: "thoughtful-gift", label: "Thoughtful gift", emoji: "🎁" }], crowdDistribution: { meal: 26, cash: 25, experience: 24, "thoughtful-gift": 25 }, dataStatus: "simulated", difficulty: "difficult" },
      { id: "crowd-025", type: "crowd", category: "CROWD", subcategory: "personal-preferences", question: "Which would people choose for a completely free evening?", options: [{ id: "friends", label: "See friends", emoji: "🧑‍🤝‍🧑" }, { id: "movie", label: "Watch a movie", emoji: "🎬" }, { id: "restaurant", label: "Try a restaurant", emoji: "🍜" }, { id: "quiet-night", label: "Quiet night in", emoji: "🕯️" }], crowdDistribution: { friends: 29, movie: 26, restaurant: 20, "quiet-night": 25 }, dataStatus: "simulated", difficulty: "difficult" }
    ],
    time: [
      { id: "time-001", type: "time", category: "TIME", question: "When was the first iPhone released?", answer: 2007, min: 1970, max: currentYear, unit: "year" },
      { id: "time-002", type: "time", category: "TIME", question: "When did the Titanic sink?", answer: 1912, min: 1800, max: currentYear, unit: "year" },
      { id: "time-003", type: "time", category: "TIME", question: "When did the first human land on the Moon?", answer: 1969, min: 1900, max: currentYear, unit: "year" },
      { id: "time-004", type: "time", category: "TIME", question: "When was Facebook founded?", answer: 2004, min: 1990, max: currentYear, unit: "year" },
      { id: "time-005", type: "time", category: "TIME", question: "When was the first Harry Potter book published?", answer: 1997, min: 1950, max: currentYear, unit: "year" },
      { id: "time-006", type: "time", category: "TIME", subcategory: "technology", question: "In what year was YouTube founded?", answer: 2005, min: 1980, max: currentYear, unit: "year", source: "YouTube Blog", sourceUrl: "https://blog.youtube/news-and-events/youtube-at-15-my-personal-journey/", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-007", type: "time", category: "TIME", subcategory: "technology", question: "In what year did CERN release the World Wide Web software into the public domain?", answer: 1993, min: 1980, max: currentYear, unit: "year", source: "CERN", sourceUrl: "https://home.cern/science/computing/the-birth-of-the-web/where-web-was-born/", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-008", type: "time", category: "TIME", subcategory: "technology", question: "In what year was the first SMS text message sent?", answer: 1992, min: 1980, max: currentYear, unit: "year", source: "Vodafone", sourceUrl: "https://www.vodafone.com/news/newsroom/technology/25-anniversary-text-message", dateChecked: "2026-10-02", difficulty: "difficult" },
      { id: "time-009", type: "time", category: "TIME", subcategory: "technology", question: "In what year was Google Inc. officially born?", answer: 1998, min: 1980, max: currentYear, unit: "year", source: "Google, Our Story", sourceUrl: "https://about.google/company-info/our-story/", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-010", type: "time", category: "TIME", subcategory: "film-tv", question: "In what year was the original Star Wars film released?", answer: 1977, min: 1950, max: currentYear, unit: "year", source: "Lucasfilm", sourceUrl: "https://www.lucasfilm.com/productions/episode-iv/", dateChecked: "2026-10-02", difficulty: "easy" },
      { id: "time-011", type: "time", category: "TIME", subcategory: "film-tv", question: "In what year did Doctor Who first debut on BBC television?", answer: 1963, min: 1950, max: currentYear, unit: "year", source: "Doctor Who official site", sourceUrl: "https://www.doctorwho.tv/news-and-features/happy-whoday-54-things-you-need-to-know-about-doctor-who", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-012", type: "time", category: "TIME", subcategory: "film-tv", question: "In what year did Netflix open its online DVD rental store?", answer: 1998, min: 1980, max: currentYear, unit: "year", source: "About Netflix", sourceUrl: "https://about.netflix.com/en/news/first-online-dvd-rental-store-opens", dateChecked: "2026-10-02", difficulty: "difficult" },
      { id: "time-013", type: "time", category: "TIME", subcategory: "music", question: "In what year was The Beatles' first UK single, 'Love Me Do', released?", answer: 1962, min: 1950, max: currentYear, unit: "year", source: "The Beatles official site", sourceUrl: "https://www.thebeatles.com/love-me-do", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-014", type: "time", category: "TIME", subcategory: "music", question: "In what year did the Live Aid concerts take place?", answer: 1985, min: 1960, max: currentYear, unit: "year", source: "National Library of Ireland", sourceUrl: "https://www.nli.ie/news-stories/news/step-back-1985-nli-live-aid-archive-goes-digital", dateChecked: "2026-10-02", difficulty: "easy" },
      { id: "time-015", type: "time", category: "TIME", subcategory: "music", question: "In what year did Spotify launch to listeners?", answer: 2008, min: 1990, max: currentYear, unit: "year", source: "Spotify Newsroom", sourceUrl: "https://newsroom.spotify.com/2023-02-01/spotifys-journey-to-200-million-subscribers/", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-016", type: "time", category: "TIME", subcategory: "sport", question: "In what year was the first FIFA World Cup held?", answer: 1930, min: 1900, max: currentYear, unit: "year", source: "FIFA", sourceUrl: "https://inside.fifa.com/en/tournaments/mens/worldcup/2018russia/news/rimet-s-world-cup-vision-realised-2927423", dateChecked: "2026-10-02", difficulty: "easy" },
      { id: "time-017", type: "time", category: "TIME", subcategory: "sport", question: "In what year were the first Wimbledon Championships held?", answer: 1877, min: 1800, max: currentYear, unit: "year", source: "The Championships, Wimbledon", sourceUrl: "https://www.wimbledon.com/en_GB/about/history", dateChecked: "2026-10-02", difficulty: "difficult" },
      { id: "time-018", type: "time", category: "TIME", subcategory: "sport", question: "In what year were the first modern Olympic Games held in Athens?", answer: 1896, min: 1800, max: currentYear, unit: "year", source: "International Olympic Committee Historical Archives", sourceUrl: "https://library.olympics.com/Default/basicfilesdownload.ashx?itemGuid=2ECE9BE9-EA5F-4F0F-97DF-84C75B6BC60A", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-019", type: "time", category: "TIME", subcategory: "british-history-culture", question: "In what year did the Metropolitan Railway, the first underground railway, open in London?", answer: 1863, min: 1800, max: currentYear, unit: "year", source: "Transport for London", sourceUrl: "https://tfl.gov.uk/info-for/media/press-releases/2014/january/time-capsule-to-be-opened-in-2063-seals-london-undergrounds-extraordinary-150th-anniversary-year", dateChecked: "2026-10-02", difficulty: "difficult" },
      { id: "time-020", type: "time", category: "TIME", subcategory: "british-history-culture", question: "In what year did the National Health Service come into effect?", answer: 1948, min: 1900, max: currentYear, unit: "year", source: "UK Parliament", sourceUrl: "https://www.parliament.uk/about/living-heritage/transformingsociety/livinglearning/coll-9-health1/health-01/nhs-act-page-2/", dateChecked: "2026-10-02", difficulty: "easy" },
      { id: "time-021", type: "time", category: "TIME", subcategory: "british-history-culture", question: "In what year was the UK Equal Franchise Act passed, giving women the vote on the same basis as men?", answer: 1928, min: 1800, max: currentYear, unit: "year", source: "UK Parliament", sourceUrl: "https://www.parliament.uk/about/living-heritage/transformingsociety/electionsvoting/womenvote/unesco/equal-franchise-act-1928/", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-022", type: "time", category: "TIME", subcategory: "world-history", question: "In what year did the Berlin Wall open and begin to fall?", answer: 1989, min: 1960, max: currentYear, unit: "year", source: "Berlin.de", sourceUrl: "https://www.berlin.de/en/history/8482274-8619314-opening-and-fall-of-the-berlin-wall.en.html", dateChecked: "2026-10-02", difficulty: "easy" },
      { id: "time-023", type: "time", category: "TIME", subcategory: "world-history", question: "In what year was Victory in Europe (VE) Day, marking Germany's surrender in the Second World War?", answer: 1945, min: 1900, max: currentYear, unit: "year", source: "Imperial War Museums", sourceUrl: "https://www.iwm.org.uk/sites/default/files/files/2025-04/veday_learning_resource.pdf", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-024", type: "time", category: "TIME", subcategory: "companies-business", question: "In what year did Amazon open its online store to customers?", answer: 1995, min: 1980, max: currentYear, unit: "year", source: "Amazon Investor Relations", sourceUrl: "https://ir.aboutamazon.com/faqs/", dateChecked: "2026-10-02", difficulty: "medium" },
      { id: "time-025", type: "time", category: "TIME", subcategory: "companies-business", question: "In what year did the McDonald brothers open their first McDonald's restaurant?", answer: 1940, min: 1900, max: currentYear, unit: "year", source: "McDonald's corporate history", sourceUrl: "https://corporate.mcdonalds.com/corpmcd/our-company/who-we-are/our-history.html", dateChecked: "2026-10-02", difficulty: "difficult" }
    ]
  };

  window.GUESSED.validateQuestionBank = function validateQuestionBank() {
    const bank = window.GUESSED.questionBank;
    const categories = ["price", "scale", "human", "crowd", "time"];
    const seenIds = new Set();
    const errors = [];

    categories.forEach((type) => {
      if (!Array.isArray(bank[type])) {
        errors.push(`Missing question category array: ${type}`);
        return;
      }
      bank[type].forEach((item, index) => {
        const path = `${type}[${index}]`;
        if (!item || typeof item !== "object") {
          errors.push(`${path} must be a question object`);
          return;
        }
        if (typeof item.id !== "string" || item.id.trim() === "") errors.push(`${path} has an empty or missing ID`);
        else if (seenIds.has(item.id)) errors.push(`${path} has duplicate ID "${item.id}"`);
        else seenIds.add(item.id);
        if (item.type !== type) errors.push(`${path} type must be "${type}"`);
        if (typeof item.category !== "string" || item.category.trim() === "") errors.push(`${path} is missing category`);
        if (typeof item.question !== "string" || item.question.trim() === "") errors.push(`${path} is missing question text`);
        if (type !== "crowd" && item.answer === undefined) errors.push(`${path} is missing answer`);
        if ((type === "scale" || type === "time") && (!Number.isFinite(item.min) || !Number.isFinite(item.max) || item.max <= item.min)) errors.push(`${path} must include a valid min and max`);
        if (type === "human" && typeof item.verified !== "boolean") errors.push(`${path} must include boolean verified metadata`);
        if (type === "crowd") {
          if (!Array.isArray(item.options)) errors.push(`${path} must include an options array`);
          if (!item.crowdDistribution || typeof item.crowdDistribution !== "object") {
            errors.push(`${path} must include a crowdDistribution object`);
          } else if (Array.isArray(item.options)) {
            const optionIds = item.options.map((option) => option && option.id).sort();
            const distributionIds = Object.keys(item.crowdDistribution).sort();
            if (optionIds.length !== distributionIds.length || optionIds.some((id, optionIndex) => id !== distributionIds[optionIndex])) {
              errors.push(`${path} distribution keys must match option IDs`);
            }
            const total = Object.values(item.crowdDistribution).reduce((sum, value) => sum + Number(value), 0);
            if (total !== 100) errors.push(`${path} crowd distribution totals ${total}, expected 100`);
          }
        }
      });
    });

    errors.forEach((error) => console.error(`[GUESSED question bank] ${error}`));
    if (errors.length === 0) console.info(`[GUESSED question bank] Validated ${seenIds.size} questions across ${categories.length} categories.`);
    return errors.length === 0;
  };

  window.GUESSED.validateQuestionBank();
})();


